version: '3.8'

services:
  backend:
    build: .
    container_name: habit-tracker-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:////tmp/habit_tracker.db
      - SECRET_KEY=${SECRET_KEY:-default-secret-key-change-in-production}
    volumes:
      - ./app:/app/app
    restart: unless-stopped
    networks:
      - habit-tracker-network

networks:
  habit-tracker-network:
    driver: bridge
