version: "3.8"

services:
  # 1. SERVICIO DE BASE DE DATOS POSTGRESQL
  db:
    image: postgres:16-alpine
    container_name: habit-tracker-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}       
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}         
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - habit-tracker-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 2. SERVICIO DE BACKEND (FASTAPI)
  backend:
    build: .
    container_name: habit-tracker-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
      - ./frontend_excel:/app/frontend_excel 
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - habit-tracker-network
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  # 3. SERVICIO DE FRONTEND (ANGULAR)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfilefront
    container_name: habit-tracker-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: always
    networks:
      - habit-tracker-network
    environment:
      NODE_ENV: production

networks:
  habit-tracker-network:
    driver: bridge

volumes:
  postgres_data:
    name: habit-tracker-postgres-data
