[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist/frontend"

[dev]
  command = "cd frontend && npm start"
  port = 4200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200